### PR TITLE
Allow user to disable server certificate validity check

### PR DESCRIPTION
**Pull request by eleksir**
* Allow user to disable ssl validity check for server' cert during ssl
  handshake. This is useful for connecting to servers with self-signed
  certificates, for example to localhost (for testing) or to corporate
  servers in internal network.

### CODE REVIEW

**Comment by toddr** [comment]
This would provide the needed change. I'm concerned this is the wrong solution to most people's problem. I suspect it'd be better to have this module default to Mozilla::CA (configurable) and then have this be the last ditch solution.

I've not looked into what would be required to do that integration.

**Comment by binfalse** [comment]
I agree, this is not the proper solution to the problem. Having an option to disable SSL verification may still be useful, I'll therefore integrate the PR

thanks for the contributions @eleksir !

**Comment by binfalse** [comment]
I agree, this is not the proper solution to the problem. Having an option to disable SSL verification may still be useful, I'd therefore vote to merge the PR

**Comment by eleksir** [comment]
Well, there is 2 cases:
1. if you want just disable validity check (server in local network or localhost with ssl-cert 'just to be encrypted')
2. if your perl unable to find ca-certificates.

This PR resolves first case.
Second case can be resolved via either integrating Mozilla::CA or via manual setting path to ca.pem. Matter of sane defaults.

**Comment by eleksir** [comment]
Couldn't resist and made PR #11 
I agree with @toddr - this will fully resolve issue #6 by providing sane default and ability to override it.

**Pull request merged**
